export const siteConfig = {
  title: 'WarTeamX Software Labs',
  author: 'WarTeamX Software Labs',
  role: 'Independent Software Laboratory',
  description:
    'An independent software laboratory focused on production-ready software, modern technologies, and practical engineering knowledge.',
  siteUrl: 'https://warteamx.github.io/blog/',
  socialImage: '/social-card.svg',
  socialHandle: '@warteamx',
  email: 'hello@warteamx.dev',
  navigation: [
    { href: '/', label: 'Home' },
    { href: '/blog/', label: 'Blog' },
    { href: '/projects/', label: 'Projects' },
    { href: '/about/', label: 'About' },
    { href: '/uses/', label: 'Uses' },
  ],
  featuredTopics: [
    'TypeScript',
    'React',
    'Node.js',
    'System Design',
    'Cloud',
    'Reliability',
    'Observability',
    'Grafana',
    'OpenTelemetry',
    'Open Source',
  ],
} as const;
